module.exports = {
  title: "實録三浦党",
  author: "岩間尹",
  language: "ja",
  size: "A5", 
  theme: "theme/theme.css",
  entry: [
    "text/0.md",
    "text/1-1.md",
    "text/1-2.md",
    "text/1-3.md",
    "text/1-4.md",
    "text/1-5.md",
    "text/1-6.md",
    "text/1-7.md",
    "text/1-8.md",
    "text/1-9.md",
    "text/2-1.md",
    "text/2-2.md",
    "text/3-1.md",
    "text/3-2.md",
    "text/4-1.md",
    "text/4-2.md",
    "text/4-3.md",
    "text/4-4.md",
    "text/4-5.md",
    "text/5.md",
    "text/6.md",
    "text/7-1.md",
    "text/7-2.md",
    "text/7-3.md",
    "text/7-4.md",
    "text/7-5.md",
    "text/7-6.md",
    "text/7-7.md",
    "text/7-8.md",
    "text/9.md",
  ],
  http: true,
  timeout: 1000000,
　
}
